[dataset]
name = MATRES
num_classes = 4
train_token_path = /data/ddao/TRE/pretrained_models/Reasoning/MATRES/cache/train/token_cache_bert.pt
train_jsonl_path = /data/ddao/TRE/pretrained_models/Reasoning/MATRES/cache/train/spacy_cache_bert.jsonl
val_token_path = /data/ddao/TRE/pretrained_models/Reasoning/MATRES/cache/valid/token_cache_bert.pt
val_jsonl_path = /data/ddao/TRE/pretrained_models/Reasoning/MATRES/cache/valid/spacy_cache_bert.jsonl
test_token_path = /data/ddao/TRE/pretrained_models/Reasoning/MATRES/cache/test/token_cache_bert.pt
test_jsonl_path = /data/ddao/TRE/pretrained_models/Reasoning/MATRES/cache/test/spacy_cache_bert.jsonl
rule_file = {ROOT}/rules/rules_MATRES.txt
relation_map = {"AFTER": 0, "BEFORE": 1, "EQUAL": 2, "VAGUE": 3}
class_weights = [1.0, 1.0, 1.0, 1.0]
vague_label_id = 3

[model]
bert_model = bert-base-uncased
freeze_bert = false
data_mode = doc
batch_size = 64
epochs = 50
lr = 2e-5
max_grad_norm = 1.0
use_amp = true
step_size = 1.0
lambda_kl = 0.1
smooth_tau = 0.05
max_steps = 50
tol = 1e-7
use_deq = false
output_option = direct_q
rule_chunk_size = 1
lambda_distill = 1.0
lambda_energy = 1.0
learn_rule_weights = true
initial_rule_weight = 0.0

[run]
eval_mode = baseline_reasoning
split = test
checkpoint_file = MATRES_baseline_reasoning_model.pt
train_mode = baseline_reasoning
max_pairs_per_doc_batch = 256
