[dataset]
name = TBD
num_classes = 6
train_token_path = /data/ddao/TRE/pretrained_models/Reasoning/TBD/cache/train/token_cache_bert.pt
train_jsonl_path = /data/ddao/TRE/pretrained_models/Reasoning/TBD/cache/train/spacy_cache_bert.jsonl
val_token_path = /data/ddao/TRE/pretrained_models/Reasoning/TBD/cache/valid/token_cache_bert.pt
val_jsonl_path = /data/ddao/TRE/pretrained_models/Reasoning/TBD/cache/valid/spacy_cache_bert.jsonl
test_token_path = /data/ddao/TRE/pretrained_models/Reasoning/TBD/cache/test/token_cache_bert.pt
test_jsonl_path = /data/ddao/TRE/pretrained_models/Reasoning/TBD/cache/test/spacy_cache_bert.jsonl
rule_file = {ROOT}/rules/rules_TBD.txt
relation_map = {"AFTER": 0, "BEFORE": 1, "INCLUDES": 2, "IS_INCLUDED": 3, "SIMULTANEOUS": 4, "VAGUE": 5}
class_weights = [1.0, 1.0, 2.0, 2.0, 2.0, 0.1]
vague_label_id = 5

[model]
bert_model = bert-base-uncased
freeze_bert = false
data_mode = doc
batch_size = 128
epochs = 50
lr = 2e-5
max_grad_norm = 1.0
use_amp = true
step_size = 1.0
lambda_kl = 0.1
lambda_entropy = 10.0
smooth_tau = 0.05
max_steps = 50
tol = 1e-4
use_deq = false
output_option = direct_q
rule_chunk_size = 1
lambda_distill = 10.0
lambda_energy = 0.1
learn_rule_weights = true
initial_rule_weight = 0.0

[run]
eval_mode = baseline_reasoning
split = test
checkpoint_file = TBD_baseline_reasoning_model.pt
train_mode = baseline_reasoning
data_mode = doc
train_batch_size = 128
train_epochs = 50
train_lr = 2e-5
max_pairs_per_doc_batch = 256
